version: 0.2

env:
  variables:
    key: "S3_BUCKET"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g newman
      - yum install -y jq

  pre_build:
    commands:
      - aws s3 cp "s3://experiments-pipeline-postman/PNN+-+Develop+env.postman_environment.json" ./test-postman/
      - aws s3 cp "s3://experiments-pipeline-postman/Tests.postman_collection.json" ./02postman/
      - cd ./test-postman
     
  build:
    commands:
      - echo Build started on `date` from dir `pwd`
      - newman run Tests.postman_collection.json --environment PNN+-+Develop+env.postman_environment.json -r junit

reports:
  JUnitReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: '02postman/newman' # Location of the reports
